### ISSUE TITLE
Certificate error after switch to alpine image

### ISSUE THREAD

**Issue by VZWKirkland** [concourse/datadog-event-resource#2]
After the change to alpine based image I am not able to post events to datadog:

```
panic: Post https://app.datadoghq.com/api/v1/events?api_key=xxx&application_key=xxx: x509: failed to load system roots and no roots provided

goroutine 1 [running]:
main.main()
	/go/src/github.com/concourse/datadog-event-resource/cmd/out/main.go:42 +0x61d
```

I hijacked the container and found /etc/ssl was missing, so I:
`apk add ca-certificates`

Then I was able to curl https://app.datadoghq.com

**Comment by vito** [comment]
sorry about that, thanks!
