### ISSUE TITLE
Allow connecting to datadog europe api

### ISSUE THREAD

**Issue by dcsg** [concourse/datadog-event-resource#9]
Hi, we use datadog europe datacenter and I noticed that this resource does not allow to connect to it.

In the go datadog api package, that this package uses, I noticed it is possible to change the datadog host by using the `DATADOG_HOST` env var, see here: https://github.com/zorkian/go-datadog-api/blob/9e2c892691035a7685a16d5839910cfc54e42fb6/client.go#L55.

I tried to set it on params on the `get` and `put` but didn't work.

Is there a way to do it? If it requires code implementation I could do it if you provide some guidelines.

Thanks in advance.

**Comment by dcsg** [comment]
@vito @chendrix is there any guidance you could give here?

Thanks

**Comment by vito** [comment]
Seems like we'd need to change the resource to accept the datadog host as a config field under `source:`.
